stages:
  - test
  - build

#
# Definitions
#

.build_job_definition:
  stage: build
  only:
    - master
    - docker
    - docker-dev
    - /^v(?:\d+\.)+\d+$/
  image: docker:18.09.2-git
  services:
    - docker:18.09.2-dind
  before_script:
    - date
    - whoami
    - cat /etc/*release
    - df -h
    - free
    #- env
    - docker version
    - docker images
    - echo "DOCKER_HOST is $DOCKER_HOST'"

    - echo "[Stage $CI_JOB_STAGE, Job $CI_JOB_NAME]"
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - apk add --no-cache git make || sudo apt-get install -y git make
    - make build "GOOS=$GOOS" "GOARCH=GOARCH"
    - make build-image push-image "GOOS=$GOOS" "GOARCH=GOARCH" "REGISTRY=$CI_REGISTRY" "REGISTRY_USER=$CI_REGISTRY_USER"
  after_script:
    - docker logout "$CI_REGISTRY"
    - docker images
    - date

#
# Jobs
#

test_job:
  stage: test
  image: docker:18.09.2-git
  services:
    - docker:18.09.2-dind
  before_script:
    - date
    - whoami
    - cat /etc/*release
    - df -h
    - free
    #- env
    - docker version
    - docker images
    - echo "DOCKER_HOST is $DOCKER_HOST'"
  script:
    - apk add --no-cache git make || sudo apt-get install -y git make
    - make test
  after_script:
    - docker logout "$CI_REGISTRY"
    - docker images
    - date

build_linux_amd64:
  extends: .build_job_definition
  variables:
    GOOS: linux
    GOARCH: amd64

build_darwin_amd64:
  extends: .build_job_definition
  variables:
    GOOS: darwin
    GOARCH: amd64

build_windows_amd64:
  extends: .build_job_definition
  variables:
    GOOS: windows
    GOARCH: amd64
