stages:
  - test
  - build_image

test_job:
  stage: test
  except:
    - master
  image: docker:18.09.2-git
  services:
    - docker:18.09.2-dind
  before_script:
    - date
    - whoami
    - cat /etc/*release
    - df -h
    - free
    #- env
    - docker version
    - docker images
    - echo "DOCKER_HOST is $DOCKER_HOST'"
  script:
    - apk add --no-cache git make || sudo apt-get install -y git make
    - make test INSTALL_GIT=true
  after_script:
    - docker logout "$CI_REGISTRY"
    - docker images
    - date

build_image_job:
  stage: build_image
  only:
    - docker
    - docker-dev
    - /^v(?:\d+\.)+\d+$/
  except:
    - master
  image: docker:18.09.2-git
  services:
    - docker:18.09.2-dind
  before_script:
    - date
    - whoami
    - cat /etc/*release
    - df -h
    - free
    #- env
    - docker version
    - docker images
    - echo "DOCKER_HOST is $DOCKER_HOST'"

    - echo "[Stage $CI_JOB_STAGE, Job $CI_JOB_NAME]"
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - apk add --no-cache git make || sudo apt-get install -y git make
    - REGISTRY="$CI_REGISTRY" REGISTRY_USER="$CI_REGISTRY_USER" make build-image push-image
  after_script:
    - docker logout "$CI_REGISTRY"
    - docker images
    - date
