stages:
  - test
  - build_image

variables:
  BIN: ${CI_PROJECT_NAME}
  APP_VERSION: $CI_COMMIT_REF_NAME
  COMMIT_SHA1: ${CI_COMMIT_SHA}
  BUILD_DIR: $CI_PROJECT_DIR/build
  BUILD_CONTEXT: .
  IMAGE_PATH: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME

test_job:
  stage: test
  except:
    - master
  image: docker:18.09.2-git
  services:
    - docker:18.09.2-dind
  before_script:
    - date
    - whoami
    - cat /etc/*release
    - df -h
    - free
    #- env
    - docker version
    - docker images
    - echo "DOCKER_HOST is $DOCKER_HOST'"
  script:
    - apk add --no-cache git make
    - make test INSTALL_GIT=true
  after_script:
    - docker logout "$CI_REGISTRY"
    - docker images
    - date

build_image_job:
  stage: build_image
  only:
    - docker
    - docker-dev
    - /^v(?:\d+\.)+\d+$/
  except:
    - master
  image: docker:18.09.2-git
  services:
    - docker:18.09.2-dind
  before_script:
    - date
    - whoami
    - cat /etc/*release
    - df -h
    - free
    #- env
    - docker version
    - docker images
    - echo "DOCKER_HOST is $DOCKER_HOST'"

    - echo "[Stage $CI_JOB_STAGE, Job $CI_JOB_NAME]"
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - |
      docker build \
        --build-arg "OS=linux" \
        --build-arg "ARCH=amd64" \
        --build-arg "BIN=${BIN}" \
        --build-arg "VERSION=${APP_VERSION}" \
        --build-arg "COMMIT_SHA1=${COMMIT_SHA1}" \
        --build-arg "BUILD_DATE=$( date '+%Y-%m-%dT%H:%M:%S%z' )" \
        --tag "${IMAGE_PATH}:${APP_VERSION}" \
        --file "${BUILD_DIR}/Dockerfile" \
        "${BUILD_CONTEXT}"
    - docker push "${IMAGE_PATH}:${APP_VERSION}"
    - docker history --no-trunc "${IMAGE_PATH}:${APP_VERSION}"
  after_script:
    - docker logout "$CI_REGISTRY"
    - docker images
    - date
