language: shell
dist: xenial
services: docker

stages:
  - test
  - build

jobs:
  include:
    - name: Unit Tests
      stage: test
      before_script:
        - date
        - whoami
        - cat /etc/*release
        - df -h
        - free
        #- env
        - docker version
        - docker images
        - echo "DOCKER_HOST is '${DOCKER_HOST}'"
      script:
        - apk add --no-cache git make || sudo apt-get install -y git make
        - sudo -s /bin/sh -c 'make test' # Force make to run docker under root user
        - bash <(curl -s https://codecov.io/bash)
      after_script:
        - date
    - name: Build
      stage: build
      branches:
        only:
          - master
          - docker
          - docker-dev
          - /^v(?:\d+\.)+\d+$/
      before_script:
        - date
        - whoami
        - cat /etc/*release
        - df -h
        - free
        #- env
        - docker version
        - docker images
        - echo "DOCKER_HOST is ${DOCKER_HOST}"

        - echo "[Stage $TRAVIS_BUILD_STAGE_NAME, Job $TRAVIS_JOB_NAME]"
        - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
      script:
        - sudo apt-get install -y git make
        - REGISTRY="$CI_REGISTRY" REGISTRY_USER="$CI_REGISTRY_USER" make build-image push-image
      after_script:
        - docker logout "$CI_REGISTRY"
        - docker images
        - date
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file:
    - ./.go/bin/*
  skip_cleanup: true
  on:
    tags: false
  draft: true
