language: shell
dist: xenial
services: docker

stages:
  - build
  - test

jobs:
  include:
    - stage: test
      before_script:
        - date
        - whoami
        - cat /etc/*release
        - df -h
        - free
        #- env
        - docker version
        - docker images
        - echo "DOCKER_HOST is '${DOCKER_HOST}'"
      script:
        - apk add --no-cache git make || sudo apt-get install -y git make
        - sudo -s /bin/sh -c 'make test INSTALL_GIT=true' # Force make to run docker under root user
      after_script:
        - date
    - stage: build_image
      branches:
        only:
          - master
          - docker
          - docker-dev
          - /^v(?:\d+\.)+\d+$/
      before_script:
        - date
        - whoami
        - cat /etc/*release
        - df -h
        - free
        #- env
        - docker version
        - docker images
        - echo "DOCKER_HOST is ${DOCKER_HOST}"

        - echo "[Stage $TRAVIS_BUILD_STAGE_NAME, Job $TRAVIS_JOB_NAME]"
        - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
      script:
        - sudo apt-get install -y git make
        - REGISTRY="$CI_REGISTRY" REGISTRY_USER="$CI_REGISTRY_USER" make build-image push-image
      after_script:
        - docker logout "$CI_REGISTRY"
        - docker images
        - date
