version: '2.2'
services:
  source-udp-forwarder:
    image: alpine:3.15
    environment:
      - UDP_LISTEN_ADDR=:26999
      - UDP_FORWARD_ADDR=127.0.0.1:27500
      - FORWARD_PROXY_KEY=XXXXX
      - FORWARD_GAMESERVER_IP=127.0.0.1
      - FORWARD_GAMESERVER_PORT=27015
      - LOG_LEVEL=DEBUG
      - LOG_FORMAT=txt
    ports:
      - 26999:26999/udp
    volumes:
      - ${OUTBIN?:err}:/${BIN?:err}
    entrypoint: /${BIN?:err}
