version: '3.4'

services:
  source_builder_exporter:
    image: alpine:3.8
    user: ${UID}:${GID}
    ports:
      - target: 26999
        published: 26999
        protocol: udp
        mode: host
    environment:
      - UDP_LISTEN_ADDR=:26999
      - UDP_FORWARD_ADDR=0.0.0.0:27500
      - FORWARD_PROXY_KEY=XXXXX
      - FORWARD_GAMESERVER_IP=127.0.0.1
      - FORWARD_GAMESERVER_PORT=27015
      - LOG_LEVEL=DEBUG
    entrypoint: /${BIN?:err}
    volumes:
      - ${OUTBIN?:err}:/${BIN?:err}
    network_mode: host
